name: Build and Cache vcpkg Dependencies

on:
  push:
    branches:
      - main

permissions:
  contents: read 
  packages: write

jobs:
  vcpkg-cache:
    runs-on: ubuntu-latest # may want to pin at some point

    env:
      # Location where vcpkg.exe will live after bootstrap
      VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg  
      # NuGet feed URL for GitHub Packages
      FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      # Instruct vcpkg to use GitHub Packages: note we reference FEED_URL literally 
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,readwrite"
      # Trying to get at why Nuget credentialling fails
      VCPKG_INSTALL_OPTIONS: "--debug"
      # Attempt to let vcpkg/nuget.exe push authenticate
      VCPKG_NUGET_TOKEN: ${{ secrets.VCPKG_PACKAGES }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # For getting Windows binaries in the linux system on github (I hope) - need to remove this if the sdk thing works
      - name: Install Mono (mono-complete)
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete

      - name: Export GitHub Actions cache variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '')
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '')

      - name: Install .NET SDK 6.x
        uses: actions/setup-dotnet@v4
        env:
          DOTNET_INSTALL_DIR: ${{ runner.temp }}/.dotnet
        with:
          dotnet-version: '6.0.x'

      - name: Clone vcpkg repository
        shell: bash
        run: |
          # Clone the official vcpkg repo
          git clone https://github.com/Microsoft/vcpkg.git vcpkg
          cd vcpkg

      - name: Bootstrap vcpkg
        shell: bash
        run: |
          cd vcpkg
          ./bootstrap-vcpkg.sh

      #- name: Configure NuGet source via dotnet
      #  shell: bash
      #  run: |
      #    dotnet nuget add source "${FEED_URL}" \
      #      --name GitHubPackages \
      #      --username "${{ github.actor }}" \
      #      --password "${{ secrets.GITHUB_TOKEN }}" \
      #      --store-password-in-clear-text
          
      #    dotnet nuget update source GitHubPackages \
      #      --username "${{ github.actor }}" \
      #      --password "${{ secrets.GITHUB_TOKEN }}" \
      #      --store-password-in-clear-text

      - name: Install vcpkg ports with binary caching
        shell: bash
        run: |
          export VCPKG_NUGET_TOKEN="${VCPKG_NUGET_TOKEN}"
          cd vcpkg
          # Install required libraries (downloads from cache if available, else builds then pushes)
          VBINARY_SOURCES="${VCPKG_BINARY_SOURCES}"
          ./vcpkg install gsl armadillo jsoncpp boost-circular-buffer
          echo "Token is set: ${VCPKG_NUGET_TOKEN:0:4}******"
