name: Build and Cache Wheel

on:
  push:
    branches:
      - main

permissions:
  contents: read                                            # allow checkout without write :contentReference[oaicite:1]{index=1}
  packages: write                                           # allow vcpkg push/pull to GitHub Packages :contentReference[oaicite:2]{index=2}

jobs:
  vcpkg-cache:
    runs-on: ubuntu-latest

    env:
      VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
      FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      VCPKG_BINARY_SOURCES: clear;nuget,${{ env.FEED_URL }},readwrite
      GH_PACKAGES_TOKEN: ${{ secrets.VCPKG_PACKAGES }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4                               # get source code :contentReference[oaicite:3]{index=3}

      - name: Restore vcpkg cache
        uses: actions/cache@v4                                  # restore previous vcpkg install trees :contentReference[oaicite:4]{index=4}
        with:
          path: |
            vcpkg/installed
            vcpkg/buildtrees
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-${{ github.sha }}

      - name: Install Mono for nuget.exe
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete                 # mono needed to run nuget.exe on Linux :contentReference[oaicite:5]{index=5}

      - name: Clone & bootstrap vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git vcpkg
          cd vcpkg
          git checkout tags/2023.10.19                          # pin to match ABI‐hashed binaries :contentReference[oaicite:6]{index=6}
          ./bootstrap-vcpkg.sh
        shell: bash

      - name: Configure NuGet feed and API key
        run: |
          nuget_path="$($VCPKG_EXE fetch nuget | tail -n1 | tr -d '\r')"
          mono "$nuget_path" sources add \
            -Name GitHubPackages \
            -Source "$FEED_URL" \
            -UserName "${{ github.repository_owner }}" \
            -Password "$GH_PACKAGES_TOKEN" \
            -StorePasswordInClearText                          # register feed :contentReference[oaicite:7]{index=7}
          mono "$nuget_path" setapikey "$GH_PACKAGES_TOKEN" -Source "$FEED_URL"  # persist API key :contentReference[oaicite:8]{index=8}
        shell: bash

      - name: Install C++ dependencies via vcpkg
        run: |
          cd vcpkg
          ./vcpkg install gsl armadillo jsoncpp boost-circular-buffer openblas lapack-reference  # pull cached binaries 
        shell: bash

      - name: Save vcpkg cache
        uses: actions/cache@v4                                  # save newly built or pulled binaries :contentReference[oaicite:10]{index=10}
        with:
          path: |
            vcpkg/installed
            vcpkg/buildtrees
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-${{ github.sha }}-postinstall

  build-wheel:
    needs: vcpkg-cache
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9','3.10']                         # build multiple Python versions :contentReference[oaicite:11]{index=11}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}         # install Python interpreter :contentReference[oaicite:12]{index=12}

      - name: Install build dependencies
        run: pip install --upgrade pip build wheel ninja cmake  # install PEP 517 and Ninja 

      - name: Build wheel with vcpkg toolchain
        env:
          SKBUILD_CMAKE_ARGS: "-G Ninja;-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        run: python -m build --wheel --outdir dist              # PEP 517 build invokes CMake → Ninja 

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: c_spikes-wheel-${{ matrix.python-version }}     # deploy built wheel :contentReference[oaicite:15]{index=15}
          path: dist/*.whl
